### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by krzaczek** [PayLane/paylane_php#1]
Witam,

Czy jest szansa żeby oficjalny klient PHP był dostosowany do instalacji poprzez composer ?

Paweł

**Comment by marcin-saja** [comment]
Dołączam do pytania.

**Comment by krzaczek** [comment]
@marcin-saja Ponieważ nie odpowiadają postanowiłem sobie sam rozwiązać problem https://github.com/freshmindpl/paylane_php#composer

**Comment by mariuskubilius** [comment]
:+1:

**Comment by krzaczek** [comment]
closed by #2
