### ISSUE TITLE
php requirements

### ISSUE THREAD

**Issue by forest90** [PayLane/paylane_php#3]
Are there serious ciurcumstances in front which that lib. require ~5.3 and disallow php 7 use it?
Could You change that req.? I had just upgrade php to 7 and that's big problem. TIA!

**Comment by Yupik** [comment]
Same thing here, @mlebkowski , could You accept pull request? There's a fix for it :)

**Comment by mlebkowski** [comment]
sure, @Yupik, but I’m not a maintainer on this repo ;)

**Comment by Yupik** [comment]
Just saw You as one of autors ;) So @PayLane please come here! :)
